### ISSUE TITLE
Confused by utility_meter sensors for Power Wheel Card when using Powerflow

### ISSUE THREAD

**Issue by mihalski** [safepay/sensor.fronius#38]
In the section `Custom Power Wheel Card (if using a Powerflow)` it describes creating a utility_meter sensor to provide the necessary information for energy monitoring, however, if using PowerFlow rather than smartmeter you have neither `sensor.fronius_smartmeter_energy_ac_consumed` nor `sensor.fronius_smartmeter_energy_ac_sold`.
Do I need to enable both powerflow and smartmeter?
Next issue is that those inputs are in MWh and I think I need them in kWh? Do I need to create a template sensor to convert it into the correct unit?

Sorry if this covered somewhere but I couldn't find it.

**Comment by nilrog** [comment]
Very late answer...

To enable all sensors named "*_smartmeter_*" you need to enable smartmeter. Enabling powerflow will only give you the sensors needed to populate the power-wheel-card. It is all mentioned in the readme ;)
They are separate options since the "smartmeter" sensors were added later, and you may not want to have all those additional sensors.

Some of the sensor units can be configured, again it is mentioned in the readme. If any units are not suitable then, yes, you can create a template sensor to convert them.
