### ISSUE TITLE
GEN24 Symo returns day_energy, year_energy and total_energy as unknown.

### ISSUE THREAD

**Issue by rafajrichard** [safepay/sensor.fronius#42]
I have a suspicion that this is disabled by Fronius to push solar.web but I want to make sure that it isn't an issue on my end.
Everything else shows up fine
![image](https://user-images.githubusercontent.com/53647672/112724522-176bf100-8f14-11eb-8044-b72c15f70962.png)

**Comment by mstoffel-sag** [comment]
Same here. Alle energy entities are unknown. Is anybody able to read those values on a GEN24?

**Comment by nilrog** [comment]
If you are still interested I have a preliminary version ready that adds support for Gen24. It corrects the sensor values for the smartmeter but cannot fix the DAY_ENERGY and YEAR_ENERGY since the are no longer supported by Fronius.
See my post in #58 for a link to my repo/branch where you can find the updated sensor.py.
